In [147]:

import pandas as pd
df= pd.read_csv('email.csv')
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [148]:
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [149]:
df['Category'].nunique()
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [150]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data= le.fit_transform(df['Category'])
df['target']= data

df

Category                                            Message  target
0         ham  Go until jurong point, crazy.. Available only ...       0
1         ham                      Ok lar... Joking wif u oni...       0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...       1
3         ham  U dun say so early hor... U c already then say...       0
4         ham  Nah I don't think he goes to usf, he lives aro...       0
...       ...                                                ...     ...
5567     spam  This is the 2nd time we have tried 2 contact u...       1
5568      ham               Will ü b going to esplanade fr home?       0
5569      ham  Pity, * was in mood for that. So...any other s...       0
5570      ham  The guy did some bitching but I acted like i'd...       0
5571      ham                         Rofl. Its true to its name       0

[5572 rows x 3 columns]

In [197]:
Y= df.target
X= df.drop(['target', 'Category'], axis='columns')
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest= train_test_split(X,Y, test_size=0.2)
xtrain

Message
474   Want 2 get laid tonight? Want real Dogging loc...
1370                   Did you try making another butt.
4976  Yar... I tot u knew dis would happen long ago ...
2195          Hi my email address has changed now it is
3963  You have been specially selected to receive a ...
...                                                 ...
4621                        THIS IS A LONG FUCKIN SHOWR
1412  somewhere out there beneath the pale moon ligh...
3157                  Long time. You remember me today.
3590  I've sent my wife your text. After we buy them...
1428  THING R GOOD THANX GOT EXAMS IN MARCH IVE DONE...

[4457 rows x 1 columns]

In [198]:
from sklearn.feature_extraction.text import CountVectorizer
v= CountVectorizer()
x_traincount= v.fit_transform(xtrain.values.reshape((-1)))
x_traincount.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [199]:
from sklearn.naive_bayes import MultinomialNB
model= MultinomialNB()
model.fit(x_traincount, ytrain)

MultinomialNB()

In [200]:
x_testcount= v.transform(xtest.values.reshape((-1)))
model.predict(x_testcount[:10])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [164]:
ytest

5547    1
2221    0
2649    0
1427    0
5276    0
       ..
1463    1
959     0
3634    0
1943    0
4232    0
Name: target, Length: 1115, dtype: int32

In [201]:
model.score(x_testcount, ytest)

0.9820627802690582

In [202]:
# Now its time to build a pipeline
from sklearn.pipeline import Pipeline

pipe= Pipeline([('CV', CountVectorizer()),( 
                 'nb', MultinomialNB())])


In [205]:
pipe.fit(xtrain.values.reshape((-1)), ytrain)

Pipeline(steps=[('CV', CountVectorizer()), ('nb', MultinomialNB())])

In [207]:
pipe.predict(xtest.values.reshape((-1)))

array([0, 0, 0, ..., 1, 1, 0])

In [209]:
pipe.score(xtest.values.reshape((-1)), ytest)

0.9820627802690582

In [225]:
#So we have the same score as without the pipeline 
n=X.values.reshape((-1))[:10]
n

array(['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...',
       'Ok lar... Joking wif u oni...',
       "Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's",
       'U dun say so early hor... U c already then say...',
       "Nah I don't think he goes to usf, he lives around here though",
       "FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, £1.50 to rcv",
       'Even my brother is not like to speak with me. They treat me like aids patent.',
       "As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune",
       'WINNER!! As a valued network customer you have been selected to receivea £900 prize reward! To claim call 090617014

In [227]:
pipe.predict(n)

array([0, 0, 1, 0, 0, 0, 0, 0, 1, 1])

In [230]:
pipe.predict(['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...',
       'Ok lar... Joking wif u oni...',
       "Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"])

array([0, 0, 1])